services:
  proyecto-ecommerce:
    container_name: proyectoEcommerce-BCH
    image: ecommerce-api:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: app.projectCholcaByron.api
    ports:
      - "8081:81"
    networks:
      - net-app-distri
    environment:
      - ASPNETCORE_ENVIRONMENT=docker

networks:
  net-app-distri:
    name: netappdistri
    external: true
