services:
  proyecto-ecommerce:
    container_name: proyectoFactura-AD
    image: factura-api:v1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROJECT_NAME: app.FacturaSubscribe
    ports:
      - "8082:82"
    networks:
      - net-app-distri
    environment:
      - ASPNETCORE_ENVIRONMENT=docker

networks:
  net-app-distri:
    name: netappdistri
    external: true
